### ISSUE TITLE
Fix Wallaby.js

### ISSUE THREAD

**Issue by SteveJRobertson** [SteveJRobertson/jam-dodger#30]
┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;SteveJRobertson&#x2F;jam-dodger&#x2F;commit&#x2F;5b627ec4b5de11b7e2f5f34bbff9a8902635b139">Enzyme installation</a>

**Comment by SteveJRobertson** [comment]
WallabyJS is broken after the attached commit.

**Comment by ArtemGovorov** [comment]
This may help:

```diff
module.exports = function (wallaby) {

    ...
    setup: wallaby => {
        ...
+       if (jestConfig.setupTestFrameworkScriptFile) {
+         jestConfig.setupTestFrameworkScriptFile = jestConfig.setupTestFrameworkScriptFile.replace('<rootDir>', wallaby.projectCacheDir);
+       }
        ...
    },

    ...
  };
};
```

We have recently changed [wallaby config sample for CRA](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app) to include the change, and looks like your is missing the change.

**Comment by SteveJRobertson** [comment]
Thanks so much for this, totally fixed again. Saved me a few hours I'm sure!
